### ISSUE TITLE
Sensible Defaults

### ISSUE THREAD

**Issue by VinSpee** [yodasw16/date-picker#12]
The plugin should have a default, unthemed version that's sensible in it's style so it can be dropped in by people who don't care to customize it.

**Comment by calvinbushor** [comment]
I agree. It is on one of our top needs. Any help is appreciated.

**Comment by yodasw16** [comment]
Made everything grayscale and got rid of the fonts
https://github.com/QuickenLoans/date-picker/tree/5035e5102c7cbc6367fd59c7bb134d7f350de0f0
