### ISSUE TITLE
Make demo link's CSS file use correct MIME type

### ISSUE THREAD

**Issue by mkelley33** [yodasw16/date-picker#22]
In this repo's description there's a link to:

http://quickenloans.github.com/date-picker currently, and it fails to load the CSS.  I opened the console in FF 27 for Mac OSX, googled the error, and it looks like the
solution would be easy per instructions found at https://rawgithub.com/.  The solution is to just change the CSS URL in the repo description from "raw.github" to "rawgithub".  I saw the currently working demo at http://codepen.io/yodasw16/pen/ysnHl  Very nice work! A screenshot to the error: 
![screenshot 2014-03-10 23 51 13](https://f.cloud.github.com/assets/213627/2381976/f3b3e70c-a8d1-11e3-8eb3-d61f01bdc665.png)
 Thanks!

**Comment by yodasw16** [comment]
Oh hey, this totally didn't work. Shouldn't have changed without testing, but since it doesn't work in both cases I'm leaving it and reopening until I have time to really fix it.
