### ISSUE TITLE
Icons haven't been optimized.

### ISSUE THREAD

**Issue by VinSpee** [yodasw16/date-picker#5]
icons.png hasn't been optimized. By running them through ImageAlpha.app and ImageOptim.app, I was able to reduce the file size from 1.88kb to 451 bytes. This is a savings of 76.01%.

**Comment by calvinbushor** [comment]
Wow. And with no negative repercussions in quality?

**Comment by VinSpee** [comment]
Yep. It was especially effective on this spritesheet because of its limited color range. [Check out what the developer did with Tweetbot's filesize](http://imageoptim.com/tweetbot.html).
